mod actions;
pub mod border;
pub mod contrast;
pub mod icons;
mod locale;
pub mod logger;
mod node;
mod plural;
mod ref_resolver;
pub mod renderer;
mod state;
mod theme;
mod validator;
mod widgets;

pub use actions::{ActionCtx, ActionRegistry};
pub use icons::IconRegistry;
pub use locale::LocaleRegistry;
pub use node::{strip_json_comments, UiNode};
pub use ref_resolver::{RefResolver, substitute_vars};
pub use renderer::{get_attr, get_margin, get_state_attr, get_state_background, parse_margin, parse_padding, render_children, render_node, resolve_state_attr, resolve_text, RenderCtx};
pub use state::StateRegistry;
pub use theme::{parse_color_value, Theme};
pub use validator::Validator;
